Initial Release
kula-app/OnLaunch-Flutter-Client pull request #2
Opened 2023-11-09 11:20 UTC by Rasakul

2023-11-27 09:34 UTC, philprime requested changes
Can we remove the `coverage_badge.svg`? I do not believe it should be checked in.

2023-11-27 09:34 UTC, philprime commented on README.md
> +TODO
Please add a description how to integrate OnLaunch

2023-12-13 11:05 UTC, Rasakul commented
@philprime true, thanks for noticing! Fixed

2023-12-14 07:55 UTC, philprime commented
Instead of removing the description I would have added in the unit tests again, but if they are unnecessary, removing them is fine too.

I removed the whole section about "Continuous Integration" from the README you missed to remove.

2023-12-14 07:56 UTC, philprime approved these changes

2023-12-14 11:35 UTC, Rasakul commented
@philprime there are no unit tests for the current version. I'd add the badge later again, when integrating the unit tests.

Thanks for fixing the Readme (again 😅)

2023-12-14 11:36 UTC, merged